default:
  adapter: postgresql
  database: 'roads_test'

  # username: roads
  # password: roads0
  # host: osm.dbx1.dryade.priv

osm:
  adapter: postgresql
  database: osm
  #username: osm
  #password: osm
  # host: osm.dryade.priv
