default:
  adapter: postgresql
  database: 'roads'

  # adapter: postgresql
  # database: roads
  # username: roads
  # password: roads0
  # host: osm.dryade.priv

osm:
  adapter: postgresql
  database: osm
  username: osm
  password: osm
  host: osm.dryade.priv
