development: 
  adapter: postgresql
  database: roads
  username: roads
  password: roads0
  template: template_postgis

test: 
  adapter: postgresql
  database: roads_test
  username: roads
  password: roads0
  template: template_postgis

osm:
  adapter: postgresql
  database: osm
  username: osm
  password: osm
  host: osm.dbx2.dryade.priv
