#!/usr/bin/env ruby

require File.expand_path('../../config/boot', __FILE__)

require 'active_osm'
require 'georuby-ext'

require 'progressbar'

# ActiveRecord::Base.logger = Logger.new("log/development.log")

progress = ProgressBar.new("OSM::Road import", OSM::Road.count)

duplicated_osm_ids = OSM::Road.connection.select_values("SELECT osm_id FROM france_osm_line GROUP BY osm_id HAVING (COUNT(osm_id) > 1)").map(&:to_i)

OSM::Road.find_in_batches do |osm_roads| 
  ActiveRoad::ActiveRecord.transaction do
    osm_roads.each do |osm_road|
      # FIXME we're ignoring splitted osm objects
      unless duplicated_osm_ids.include?(osm_road.osm_id)
        attributes = {
          :objectid => "osm:#{osm_road.osm_id}", 
          :name => osm_road.name, 
          :geometry => GeoRuby::SimpleFeatures::MultiLineString.from_line_strings([osm_road.geometry.to_wgs84], 4326)
        }
        ActiveRoad::Base.create! attributes
      end
      progress.inc
    end
  end
end
